// Generated by CoffeeScript 1.9.2
var SMG_DOMAIN, SMG_SEASONS, SMG_SEASONS_KEY, SMG_URL, colors, current_season, download, download_images, fetch, fetch_seasons, fs, get_next_page, get_seasons, num, output, req;

req = require("req-fast");

fs = require("fs");

download = require("download-file");

colors = require("colors");

SMG_URL = "http://www.smudgestore.com/smudge_store/public/en/index/index/category/refucoreca";

SMG_DOMAIN = "http://www.smudgestore.com";

SMG_SEASONS = {};

SMG_SEASONS_KEY = [];

current_season = 0;

num = 0;

output = "output";

fetch = function() {
  return req(SMG_URL, function(err, res) {
    var body, seasons, seasons_key;
    body = res.body;
    if (body) {
      seasons = get_seasons(body);
      SMG_SEASONS = seasons;
      seasons_key = Object.keys(seasons);
      SMG_SEASONS_KEY = seasons_key;
      return fetch_seasons(seasons_key[current_season]);
    }
  });
};

get_seasons = function(body) {
  var end, reg, result, seasons, seasons_list, start;
  start = "<div class=\"navi-title\">SEASON</div>";
  end = "<div class=\"navi-title\">SPECIAL</div>";
  body = body.replace(/\n|\t/g, "");
  result = {};
  reg = new RegExp(start + "(.*)" + end, "g");
  seasons = (body.match(reg))[0];
  seasons_list = seasons.match(/<a href=\"\/smudge_store.*?<\/a>/g);
  seasons_list.map(function(item) {
    var cat, link;
    link = (item.match(/<a href="(.*?)">/))[1];
    cat = (item.match(/<p>(.*?)<\/p>/))[1];
    cat = cat.replace(/\s/g, "").replace(/\//g, "");
    return result[cat] = link;
  });
  return result;
};

fetch_seasons = function(season, link) {
  link = SMG_DOMAIN + (link || SMG_SEASONS[season]);
  console.log(("start " + link).yellow);
  return req(link, function(err, res) {
    var _imgs, body, imgs, next;
    body = res.body;
    body = body.replace(/\n|\t/g, "");
    body = body.replace('<img src="images/logo.jpg" />', "");
    imgs = [];
    _imgs = body.match(/img src=".*?" width="80"/g);
    next = get_next_page(body);
    _imgs.map(function(item) {
      return imgs.push((item.match(/(images.*?jpg)/))[0]);
    });
    return download_images(imgs, season, next);
  });
};

get_next_page = function(body) {
  var _next, next;
  next = "";
  _next = (body.match(/margin-left: 12px;(.*?)<a href="(.*?)" class="pageNext"><\/a>/g)) || [];
  if (_next[0]) {
    next = (_next[0].match(/href="(.*?)"/))[1];
  }
  return next;
};

download_images = function(images, season, next) {
  var down;
  if (images == null) {
    images = [];
  }
  down = function(index) {
    var image_name, image_url, item;
    item = images[index];
    if (!item) {
      if (next) {
        fetch_seasons(season, next);
      } else {
        current_season += 1;
        if (SMG_SEASONS_KEY[current_season]) {
          fetch_seasons(SMG_SEASONS_KEY[current_season]);
        } else {
          console.log("---download " + num + " images---");
        }
      }
      return false;
    }
    image_name = (item.match(/list\/(.*?.jpg)/))[1];
    image_url = SMG_DOMAIN + "/smudge_store/public/" + item;
    image_url = image_url.replace("list", "demo");
    return req(image_url, function(err, res) {
      var directory;
      directory = output + "/" + season;
      return download(image_url, {
        directory: directory,
        filename: image_name
      }, function(err) {
        var color;
        if (err) {
          console.log(image_url, err);
          color = "red";
        } else {
          color = "green";
        }
        console.log(image_url[color]);
        num++;
        return down(index + 1);
      });
    });
  };
  return down(0);
};

fetch();
